version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application...
      - python3 weather.py
      - pytest
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
