global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090

 - job_name: node
   static_configs:
    - targets:
       - node-exporter:9100

 - job_name: webapp
   static_configs:
    - targets:
       - 172.31.41.142:5000

 - job_name: node_web_exporter
   static_configs:
    - targets:
       - 172.31.41.142:9100
