groups:
 - name: example
   rules:
   - alert: InstanceDown
     expr: up == 0
     for: 10s
     labels:
       severity: page
     annotations:
       summary: "Instance {{ $labels.instance }} down"
       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 10 seconds."

   - alert: HighRequestLatency
     expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
     for: 10m
     labels:
       severity: page
     annotations:
       summary: High request latency

   - alert: InstanceDown
     expr: up{instance="3.67.11.217:9100"} == 0
     for: 10s
     labels:
       severity: "critical"
