apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: devopsgoofy/weather-webapp:f66922d2d14e2feb38fda549af0405f37f8d36d5
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: regcred
