apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: devopsgoofy/weather-webapp:a0f2482257767da3faefa1c56659acc33c8b8895
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: regcred
